### ISSUE TITLE
Parallelization of FHE operations in both FheBool and FheUint8

### ISSUE THREAD

**Issue by lovely-necromancer** [gausslabs/phantom-zone#38]
Hey,
Thanks for the awesome project. 
I've been playing with it lately and did some little implementations using the examples provided.

So, I have a line that looks like this using FheBool: 
```
// Perform XOR operation on encrypted values
let enc_out: Vec<_> = enc_m0.iter().zip(enc_m1.iter()).map(|(a, b)| a ^ b).collect();
```

I want to make it parallel:
```
use rayon::prelude::*;

let enc_out: Vec<_> = enc_m0.par_iter().zip(enc_m1.par_iter()).map(|(a, b)| a ^ b).collect();
```

But I get errors like this:
```
thread '<unnamed>' panicked at src/bool/ni_mp_api.rs:169:60:
Parameters not set
thread '<unnamed>' panicked at src/bool/ni_mp_api.rs:169:60:
Parameters not set
thread '<unnamed>' panicked at src/bool/ni_mp_api.rs:169:60:
Parameters not set
```

can you help me what should I set? I've seen from your commits that did paralelization for key-aggregation that you set some stuff. but I didn't understand well.

Any help is appreciated :smiley:

**Comment by lovely-necromancer** [comment]
The exact code is in here:

https://github.com/proteus-photos/proteus-aegis/blob/15073cf401100a1c845054071be0850cb579c939/proteus/non_interactive_fhebool.rs#L70
